# Generated by Django 2.0.7 on 2019-02-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_star', models.FloatField(max_length=15)),
                ('movie_description', models.TextField(default='Description', max_length=5000)),
                ('movie_pic', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character', models.CharField(max_length=100)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='scrape.Movie')),
            ],
        ),
    ]
